---
downloads: ~/.ansible-downloads/

configure_dotfiles: true
configure_dock: true

dockitems_remove:
  - Maps
  - TV
  - Podcasts
  - News
  - "App Store"
  - Music
  - Freeform
  - Contacts
  - Calendar
  - Reminders
  - Notes
  - Messages
  - FaceTime
  - Photos
  - Mail
  - Safari
dockitems_persist:
  - name: "Google Chrome"
    path: "/Applications/Google Chrome.app/"
    pos: 2
  - name: "Slack"
    path: "/Applications/Slack.app/"
    pos: 3
  - name: iTerm
    path: "/Applications/iTerm.app/"
    pos: 4
  - name: "Visual Studio Code"
    path: "/Applications/Visual Studio Code.app/"
    pos: 5

dotfiles_repo: https://github.com/FullStackIndustries/dotfiles.git
dotfiles_repo_version: main
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/Developer/GitHub/dotfiles
dotfiles_files:
  - .zshrc

homebrew_installed_packages:
  - git
  - github/gh/gh
  - nvm

homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_cask_appdir: /Applications

homebrew_cask_apps:
  - 1password
  - google-drive
  - iterm2
  - dbeaver-community
  - docker
  - firefox
  - google-chrome
  - slack
  - transmit
  - visual-studio-code
  - local
  - figma
